### ISSUE TITLE
Can't activate Rhino 3D *solved*

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Rhino-3D---Linux-Wine-Version-#1]
### Can't activate Rhino 3D

The problem is, i can't see the windows and so it's not possible to enter the license!

![error_license](https://user-images.githubusercontent.com/79079633/119482748-85863600-bd54-11eb-9d2d-971cd007edcb.png)

**Comment by cryinkfly** [comment]
I have tested Rhino3D with Lutris, but I get a blank window, where I can activate this program:

Original:

![Bildschirmfoto_2021-07-20_11-32-23](https://user-images.githubusercontent.com/79079633/126298659-43a23eab-5fca-46bd-a818-5a34aa2ea8b7.png)

On my system:

![Bildschirmfoto_2021-07-20_11-33-17](https://user-images.githubusercontent.com/79079633/126298933-ef5fde5e-3160-450c-a1e2-50fe74a86907.png)


And here is my log file: [rhino3d-lutris-log.txt](https://github.com/cryinkfly/Rhino-3D---Linux-Wine-Version-/files/6847150/rhino3d-lutris-log.txt)

**Comment by cryinkfly** [comment]
I have solved this problem!

![Bildschirmfoto_2021-07-20_12-10-46](https://user-images.githubusercontent.com/79079633/126308306-5a0c67ab-40b6-4b13-8c3f-42574079c02c.png)

**Comment by jesterKing** [comment]
It would be good to document in this issue what exactly you did to fix the problem.
